// Copyright 2017 Stefan Schmidt
#ifndef _CONFIGURATION_H_
#define _CONFIGURATION_H_


#define VERSION_MAJOR   0
#define VERSION_MINOR   4
#define VERSION_REV     1

#define USE_SOFT_I2C

//#define USE_SSL
#define ENABLE_TEMP_INSIDE
#define ENABLE_TEMP_OUTSIDE
//#define USE_LOW_MHZ

#define TEMP_OFFSET_HTU21D 0.0f
#define TEMP_OFFSET_BME280 (0.0f)


#define SENSOR_ID_ENV_INSIDE 1
#define SENSOR_ID_ENV_OUTSIDE 2

#define BME_PIN_SDA 23 
#define BME_PIN_SCL 19 
#define BME_FREQUENCY 100000

#define HTU_PIN_SDA 21 
#define HTU_PIN_SCL 22 
#define HTU_FREQUENCY 100000

#define MAX_OPEN_CONNECTIONS 4
#define MAX_CONNECTIONS 15

#define BT_CMD_QUEUE_LEN 20
#define MQTT_RESPONSE_QUEUE_LEN 20

#define IDLE_AFTER_MS (30*1000)
#define SLEEP_IDLE_TIME 100
#define SLEEP_WORK_TIME 10

#define UPDATE_INTERVAL_TEMP (3*60*1000)

#define TRACE_LEVEL 25


#endif